// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: analysis.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAnalysisJob = `-- name: CreateAnalysisJob :one
INSERT INTO analysis_jobs (
  organization_id,
  recording_id,
  analysis_run_id,
  idempotency_key
) VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, recording_id, analysis_run_id, status, progress, idempotency_key, queue_task_id, attempt_count, last_error, locked_at, started_at, completed_at, created_at, updated_at
`

type CreateAnalysisJobParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	RecordingID    uuid.UUID `json:"recording_id"`
	AnalysisRunID  uuid.UUID `json:"analysis_run_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) CreateAnalysisJob(ctx context.Context, arg CreateAnalysisJobParams) (AnalysisJob, error) {
	row := q.db.QueryRow(ctx, createAnalysisJob,
		arg.OrganizationID,
		arg.RecordingID,
		arg.AnalysisRunID,
		arg.IdempotencyKey,
	)
	var i AnalysisJob
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RecordingID,
		&i.AnalysisRunID,
		&i.Status,
		&i.Progress,
		&i.IdempotencyKey,
		&i.QueueTaskID,
		&i.AttemptCount,
		&i.LastError,
		&i.LockedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAnalysisRun = `-- name: CreateAnalysisRun :one
INSERT INTO analysis_runs (
  organization_id,
  recording_id,
  provider,
  model,
  prompt_version,
  normalization_version,
  grouping_version,
  status,
  created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, 'QUEUED', $8)
RETURNING id, organization_id, recording_id, provider, model, prompt_version, normalization_version, grouping_version, status, raw_text, error, input_tokens, output_tokens, thinking_tokens, total_tokens, estimated_cost_usd, pricing_version, started_at, completed_at, created_by, created_at, updated_at
`

type CreateAnalysisRunParams struct {
	OrganizationID       uuid.UUID   `json:"organization_id"`
	RecordingID          uuid.UUID   `json:"recording_id"`
	Provider             string      `json:"provider"`
	Model                pgtype.Text `json:"model"`
	PromptVersion        string      `json:"prompt_version"`
	NormalizationVersion string      `json:"normalization_version"`
	GroupingVersion      string      `json:"grouping_version"`
	CreatedBy            pgtype.Text `json:"created_by"`
}

func (q *Queries) CreateAnalysisRun(ctx context.Context, arg CreateAnalysisRunParams) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, createAnalysisRun,
		arg.OrganizationID,
		arg.RecordingID,
		arg.Provider,
		arg.Model,
		arg.PromptVersion,
		arg.NormalizationVersion,
		arg.GroupingVersion,
		arg.CreatedBy,
	)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RecordingID,
		&i.Provider,
		&i.Model,
		&i.PromptVersion,
		&i.NormalizationVersion,
		&i.GroupingVersion,
		&i.Status,
		&i.RawText,
		&i.Error,
		&i.InputTokens,
		&i.OutputTokens,
		&i.ThinkingTokens,
		&i.TotalTokens,
		&i.EstimatedCostUsd,
		&i.PricingVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (
  aggregate_type,
  aggregate_id,
  event_type,
  payload
) VALUES ($1, $2, $3, $4)
RETURNING id, aggregate_type, aggregate_id, event_type, payload, attempts, available_at, published_at, last_error, created_at
`

type CreateOutboxEventParams struct {
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Attempts,
		&i.AvailableAt,
		&i.PublishedAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const listAnalysisRuns = `-- name: ListAnalysisRuns :many
SELECT id, organization_id, recording_id, provider, model, prompt_version, normalization_version, grouping_version, status, raw_text, error, input_tokens, output_tokens, thinking_tokens, total_tokens, estimated_cost_usd, pricing_version, started_at, completed_at, created_by, created_at, updated_at
FROM analysis_runs
WHERE organization_id = $1
  AND ($2::uuid IS NULL OR recording_id = $2)
ORDER BY created_at DESC
`

type ListAnalysisRunsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Column2        uuid.UUID `json:"column_2"`
}

func (q *Queries) ListAnalysisRuns(ctx context.Context, arg ListAnalysisRunsParams) ([]AnalysisRun, error) {
	rows, err := q.db.Query(ctx, listAnalysisRuns, arg.OrganizationID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalysisRun{}
	for rows.Next() {
		var i AnalysisRun
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RecordingID,
			&i.Provider,
			&i.Model,
			&i.PromptVersion,
			&i.NormalizationVersion,
			&i.GroupingVersion,
			&i.Status,
			&i.RawText,
			&i.Error,
			&i.InputTokens,
			&i.OutputTokens,
			&i.ThinkingTokens,
			&i.TotalTokens,
			&i.EstimatedCostUsd,
			&i.PricingVersion,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOutboxEvents = `-- name: LockOutboxEvents :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, attempts, available_at, published_at, last_error, created_at
FROM outbox_events
WHERE published_at IS NULL
  AND available_at <= now()
ORDER BY created_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) LockOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, lockOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Attempts,
			&i.AvailableAt,
			&i.PublishedAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox_events
SET attempts = attempts + 1,
    last_error = $2,
    available_at = now() + LEAST(interval '5 minutes', make_interval(secs => power(2, LEAST(attempts, 8))::int))
WHERE id = $1
`

type MarkOutboxFailedParams struct {
	ID        uuid.UUID   `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, arg.ID, arg.LastError)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox_events
SET published_at = now(), attempts = attempts + 1, last_error = NULL
WHERE id = $1
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}
