// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type JobStatus string

const (
	JobStatusQUEUED     JobStatus = "QUEUED"
	JobStatusPROCESSING JobStatus = "PROCESSING"
	JobStatusCOMPLETED  JobStatus = "COMPLETED"
	JobStatusFAILED     JobStatus = "FAILED"
	JobStatusCANCELLED  JobStatus = "CANCELLED"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type RecordingStatus string

const (
	RecordingStatusPENDINGUPLOAD RecordingStatus = "PENDING_UPLOAD"
	RecordingStatusUPLOADED      RecordingStatus = "UPLOADED"
	RecordingStatusPROCESSING    RecordingStatus = "PROCESSING"
	RecordingStatusANALYZED      RecordingStatus = "ANALYZED"
	RecordingStatusFAILED        RecordingStatus = "FAILED"
)

func (e *RecordingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecordingStatus(s)
	case string:
		*e = RecordingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RecordingStatus: %T", src)
	}
	return nil
}

type NullRecordingStatus struct {
	RecordingStatus RecordingStatus `json:"recording_status"`
	Valid           bool            `json:"valid"` // Valid is true if RecordingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecordingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RecordingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecordingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecordingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecordingStatus), nil
}

type RunStatus string

const (
	RunStatusQUEUED      RunStatus = "QUEUED"
	RunStatusPROCESSING  RunStatus = "PROCESSING"
	RunStatusNORMALIZING RunStatus = "NORMALIZING"
	RunStatusCOMPLETED   RunStatus = "COMPLETED"
	RunStatusFAILED      RunStatus = "FAILED"
	RunStatusCANCELLED   RunStatus = "CANCELLED"
)

func (e *RunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunStatus(s)
	case string:
		*e = RunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RunStatus: %T", src)
	}
	return nil
}

type NullRunStatus struct {
	RunStatus RunStatus `json:"run_status"`
	Valid     bool      `json:"valid"` // Valid is true if RunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunStatus), nil
}

type ActionEvent struct {
	ID                uuid.UUID          `json:"id"`
	RecordingID       uuid.UUID          `json:"recording_id"`
	AnalysisRunID     uuid.NullUUID      `json:"analysis_run_id"`
	TimestampMs       int32              `json:"timestamp_ms"`
	CanonicalAction   string             `json:"canonical_action"`
	EventType         string             `json:"event_type"`
	Screen            string             `json:"screen"`
	EntityType        pgtype.Text        `json:"entity_type"`
	EntityID          pgtype.Text        `json:"entity_id"`
	OrderID           pgtype.Text        `json:"order_id"`
	IssueType         pgtype.Text        `json:"issue_type"`
	Target            string             `json:"target"`
	Confidence        float64            `json:"confidence"`
	SourceRawEventIds []byte             `json:"source_raw_event_ids"`
	QualityFlags      []byte             `json:"quality_flags"`
	Payload           []byte             `json:"payload"`
	Source            string             `json:"source"`
	QaStatus          pgtype.Text        `json:"qa_status"`
	QaComment         pgtype.Text        `json:"qa_comment"`
	Version           int32              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type AnalysisJob struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	RecordingID    uuid.UUID          `json:"recording_id"`
	AnalysisRunID  uuid.UUID          `json:"analysis_run_id"`
	Status         JobStatus          `json:"status"`
	Progress       int16              `json:"progress"`
	IdempotencyKey string             `json:"idempotency_key"`
	QueueTaskID    pgtype.Text        `json:"queue_task_id"`
	AttemptCount   int32              `json:"attempt_count"`
	LastError      pgtype.Text        `json:"last_error"`
	LockedAt       pgtype.Timestamptz `json:"locked_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AnalysisRun struct {
	ID                   uuid.UUID          `json:"id"`
	OrganizationID       uuid.UUID          `json:"organization_id"`
	RecordingID          uuid.UUID          `json:"recording_id"`
	Provider             string             `json:"provider"`
	Model                pgtype.Text        `json:"model"`
	PromptVersion        string             `json:"prompt_version"`
	NormalizationVersion string             `json:"normalization_version"`
	GroupingVersion      string             `json:"grouping_version"`
	Status               RunStatus          `json:"status"`
	RawText              pgtype.Text        `json:"raw_text"`
	Error                pgtype.Text        `json:"error"`
	InputTokens          pgtype.Int8        `json:"input_tokens"`
	OutputTokens         pgtype.Int8        `json:"output_tokens"`
	ThinkingTokens       pgtype.Int8        `json:"thinking_tokens"`
	TotalTokens          pgtype.Int8        `json:"total_tokens"`
	EstimatedCostUsd     pgtype.Numeric     `json:"estimated_cost_usd"`
	PricingVersion       pgtype.Text        `json:"pricing_version"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	CreatedBy            pgtype.Text        `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type AnalystReport struct {
	ID                   uuid.UUID          `json:"id"`
	RecordingID          uuid.UUID          `json:"recording_id"`
	AnalysisRunID        uuid.NullUUID      `json:"analysis_run_id"`
	Summary              string             `json:"summary"`
	Observations         []byte             `json:"observations"`
	Recommendations      []byte             `json:"recommendations"`
	Metrics              []byte             `json:"metrics"`
	GraphSummary         []byte             `json:"graph_summary"`
	Model                string             `json:"model"`
	Provider             pgtype.Text        `json:"provider"`
	PromptVersion        pgtype.Text        `json:"prompt_version"`
	NormalizationVersion pgtype.Text        `json:"normalization_version"`
	GroupingVersion      pgtype.Text        `json:"grouping_version"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type AutomationCandidate struct {
	ID            uuid.UUID          `json:"id"`
	TemplateID    uuid.UUID          `json:"template_id"`
	Title         string             `json:"title"`
	Type          pgtype.Text        `json:"type"`
	Rationale     string             `json:"rationale"`
	AffectedSteps []byte             `json:"affected_steps"`
	Impact        string             `json:"impact"`
	Confidence    float64            `json:"confidence"`
	Score         float64            `json:"score"`
	Status        string             `json:"status"`
	Breakdown     []byte             `json:"breakdown"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type BoundaryRule struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	Priority       int32              `json:"priority"`
	Type           string             `json:"type"`
	Conditions     []byte             `json:"conditions"`
	Version        string             `json:"version"`
	Enabled        bool               `json:"enabled"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DataQualityIssue struct {
	ID               uuid.UUID          `json:"id"`
	RecordingID      uuid.UUID          `json:"recording_id"`
	AnalysisRunID    uuid.NullUUID      `json:"analysis_run_id"`
	RawVisionEventID uuid.NullUUID      `json:"raw_vision_event_id"`
	ActionEventID    uuid.NullUUID      `json:"action_event_id"`
	Type             string             `json:"type"`
	Severity         string             `json:"severity"`
	Message          string             `json:"message"`
	TimestampMs      int32              `json:"timestamp_ms"`
	Resolved         bool               `json:"resolved"`
	Payload          []byte             `json:"payload"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type GroundTruthEvent struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	RecordingID    uuid.NullUUID      `json:"recording_id"`
	TimestampMs    int32              `json:"timestamp_ms"`
	Payload        []byte             `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type JobAttempt struct {
	ID            uuid.UUID          `json:"id"`
	AnalysisJobID uuid.UUID          `json:"analysis_job_id"`
	Attempt       int32              `json:"attempt"`
	Status        JobStatus          `json:"status"`
	WorkerID      pgtype.Text        `json:"worker_id"`
	Error         pgtype.Text        `json:"error"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type KnownScenario struct {
	OrganizationID   uuid.UUID          `json:"organization_id"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	IssueType        string             `json:"issue_type"`
	EntityType       pgtype.Text        `json:"entity_type"`
	StartActions     []byte             `json:"start_actions"`
	RequiredActions  []byte             `json:"required_actions"`
	OptionalActions  []byte             `json:"optional_actions"`
	EndActions       []byte             `json:"end_actions"`
	ForbiddenActions []byte             `json:"forbidden_actions"`
	TimeoutMs        int32              `json:"timeout_ms"`
	Version          string             `json:"version"`
	Enabled          bool               `json:"enabled"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Organization struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OutboxEvent struct {
	ID            uuid.UUID          `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   uuid.UUID          `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	Attempts      int32              `json:"attempts"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type RawVisionEvent struct {
	ID             uuid.UUID          `json:"id"`
	AnalysisRunID  uuid.UUID          `json:"analysis_run_id"`
	TimestampMs    int32              `json:"timestamp_ms"`
	Screen         string             `json:"screen"`
	VisibleText    pgtype.Text        `json:"visible_text"`
	Target         pgtype.Text        `json:"target"`
	EventTypeGuess string             `json:"event_type_guess"`
	ColorCues      []byte             `json:"color_cues"`
	StateChange    pgtype.Text        `json:"state_change"`
	Confidence     float64            `json:"confidence"`
	Payload        []byte             `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Recording struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	OriginalName   string             `json:"original_name"`
	MimeType       string             `json:"mime_type"`
	SizeBytes      int64              `json:"size_bytes"`
	DurationSec    pgtype.Float8      `json:"duration_sec"`
	Status         RecordingStatus    `json:"status"`
	Source         string             `json:"source"`
	ObjectKey      string             `json:"object_key"`
	ChecksumSha256 pgtype.Text        `json:"checksum_sha256"`
	CreatedBy      pgtype.Text        `json:"created_by"`
	UpdatedBy      pgtype.Text        `json:"updated_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ScenarioGraph struct {
	ID            uuid.UUID          `json:"id"`
	RecordingID   uuid.UUID          `json:"recording_id"`
	AnalysisRunID uuid.NullUUID      `json:"analysis_run_id"`
	Graph         []byte             `json:"graph"`
	Metrics       []byte             `json:"metrics"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ScenarioInstance struct {
	ID                  uuid.UUID          `json:"id"`
	RecordingID         uuid.UUID          `json:"recording_id"`
	AnalysisRunID       uuid.NullUUID      `json:"analysis_run_id"`
	TemplateID          uuid.NullUUID      `json:"template_id"`
	KnownScenarioCode   pgtype.Text        `json:"known_scenario_code"`
	OrderID             pgtype.Text        `json:"order_id"`
	EntityType          pgtype.Text        `json:"entity_type"`
	EntityID            pgtype.Text        `json:"entity_id"`
	IssueType           string             `json:"issue_type"`
	StartedAtMs         int32              `json:"started_at_ms"`
	EndedAtMs           int32              `json:"ended_at_ms"`
	DurationMs          int32              `json:"duration_ms"`
	EventIds            []byte             `json:"event_ids"`
	Outcome             string             `json:"outcome"`
	Status              string             `json:"status"`
	Confidence          float64            `json:"confidence"`
	BoundaryRuleVersion pgtype.Text        `json:"boundary_rule_version"`
	QualityFlags        []byte             `json:"quality_flags"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type ScenarioTemplate struct {
	ID                  uuid.UUID          `json:"id"`
	OrganizationID      uuid.UUID          `json:"organization_id"`
	Code                pgtype.Text        `json:"code"`
	Name                string             `json:"name"`
	IssueType           string             `json:"issue_type"`
	Signature           string             `json:"signature"`
	Frequency           int32              `json:"frequency"`
	AverageDurationMs   int32              `json:"average_duration_ms"`
	MedianDurationMs    int32              `json:"median_duration_ms"`
	P95DurationMs       int32              `json:"p95_duration_ms"`
	ManualCheckCount    int32              `json:"manual_check_count"`
	RepeatedActionCount int32              `json:"repeated_action_count"`
	ConfidenceAverage   float64            `json:"confidence_average"`
	AmbiguousCount      int32              `json:"ambiguous_count"`
	AutomationScore     float64            `json:"automation_score"`
	ActionSequence      []byte             `json:"action_sequence"`
	Metrics             []byte             `json:"metrics"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type SettingsAuditLog struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ActorID        pgtype.Text        `json:"actor_id"`
	EntityType     string             `json:"entity_type"`
	EntityID       string             `json:"entity_id"`
	BeforeValue    []byte             `json:"before_value"`
	AfterValue     []byte             `json:"after_value"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
