// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: recordings.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeRecordingUpload = `-- name: CompleteRecordingUpload :one
UPDATE recordings
SET status = 'UPLOADED', updated_at = now(), updated_by = $3
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, original_name, mime_type, size_bytes, duration_sec, status, source, object_key, checksum_sha256, created_by, updated_by, created_at, updated_at
`

type CompleteRecordingUploadParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	UpdatedBy      pgtype.Text `json:"updated_by"`
}

func (q *Queries) CompleteRecordingUpload(ctx context.Context, arg CompleteRecordingUploadParams) (Recording, error) {
	row := q.db.QueryRow(ctx, completeRecordingUpload, arg.ID, arg.OrganizationID, arg.UpdatedBy)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.DurationSec,
		&i.Status,
		&i.Source,
		&i.ObjectKey,
		&i.ChecksumSha256,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecording = `-- name: CreateRecording :one
INSERT INTO recordings (
  organization_id,
  original_name,
  mime_type,
  size_bytes,
  status,
  object_key,
  created_by
) VALUES ($1, $2, $3, $4, 'PENDING_UPLOAD', $5, $6)
RETURNING id, organization_id, original_name, mime_type, size_bytes, duration_sec, status, source, object_key, checksum_sha256, created_by, updated_by, created_at, updated_at
`

type CreateRecordingParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	OriginalName   string      `json:"original_name"`
	MimeType       string      `json:"mime_type"`
	SizeBytes      int64       `json:"size_bytes"`
	ObjectKey      string      `json:"object_key"`
	CreatedBy      pgtype.Text `json:"created_by"`
}

func (q *Queries) CreateRecording(ctx context.Context, arg CreateRecordingParams) (Recording, error) {
	row := q.db.QueryRow(ctx, createRecording,
		arg.OrganizationID,
		arg.OriginalName,
		arg.MimeType,
		arg.SizeBytes,
		arg.ObjectKey,
		arg.CreatedBy,
	)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.DurationSec,
		&i.Status,
		&i.Source,
		&i.ObjectKey,
		&i.ChecksumSha256,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecording = `-- name: DeleteRecording :one
DELETE FROM recordings
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, original_name, mime_type, size_bytes, duration_sec, status, source, object_key, checksum_sha256, created_by, updated_by, created_at, updated_at
`

type DeleteRecordingParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteRecording(ctx context.Context, arg DeleteRecordingParams) (Recording, error) {
	row := q.db.QueryRow(ctx, deleteRecording, arg.ID, arg.OrganizationID)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.DurationSec,
		&i.Status,
		&i.Source,
		&i.ObjectKey,
		&i.ChecksumSha256,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecording = `-- name: GetRecording :one
SELECT id, organization_id, original_name, mime_type, size_bytes, duration_sec, status, source, object_key, checksum_sha256, created_by, updated_by, created_at, updated_at
FROM recordings
WHERE id = $1 AND organization_id = $2
`

type GetRecordingParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetRecording(ctx context.Context, arg GetRecordingParams) (Recording, error) {
	row := q.db.QueryRow(ctx, getRecording, arg.ID, arg.OrganizationID)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.DurationSec,
		&i.Status,
		&i.Source,
		&i.ObjectKey,
		&i.ChecksumSha256,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecordings = `-- name: ListRecordings :many
SELECT id, organization_id, original_name, mime_type, size_bytes, duration_sec, status, source, object_key, checksum_sha256, created_by, updated_by, created_at, updated_at
FROM recordings
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRecordings(ctx context.Context, organizationID uuid.UUID) ([]Recording, error) {
	rows, err := q.db.Query(ctx, listRecordings, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recording{}
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OriginalName,
			&i.MimeType,
			&i.SizeBytes,
			&i.DurationSec,
			&i.Status,
			&i.Source,
			&i.ObjectKey,
			&i.ChecksumSha256,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecordingStatus = `-- name: UpdateRecordingStatus :exec
UPDATE recordings
SET status = $3, updated_at = now()
WHERE id = $1 AND organization_id = $2
`

type UpdateRecordingStatusParams struct {
	ID             uuid.UUID       `json:"id"`
	OrganizationID uuid.UUID       `json:"organization_id"`
	Status         RecordingStatus `json:"status"`
}

func (q *Queries) UpdateRecordingStatus(ctx context.Context, arg UpdateRecordingStatusParams) error {
	_, err := q.db.Exec(ctx, updateRecordingStatus, arg.ID, arg.OrganizationID, arg.Status)
	return err
}
